name: Lint and Test

on:
  workflow_call:
    inputs:
      node-version:
        description: "The version of node to use"
        required: false
        type: string
        default: "latest"
      junit-report-path:
        description: "The path to the JUnit report"
        required: false
        type: string
        default: "reports/junit.xml"
      cobertura-report-path:
        description: "The path to the Cobertura report"
        required: false
        type: string
        default: "reports/coverage/cobertura-coverage.xml"
      cache-name:
        description: "The name to assign to the cache"
        required: false
        type: string
        default: pure-dependencies
    secrets:
      GH_TOKEN:
        required: true
    outputs:
      new-release-published:
        description: "If a new release was published"
        value: ${{ jobs.verify.outputs.new-release-published }}
      new-release-version:
        description: "The version of the new release"
        value: ${{ jobs.verify.outputs.new-release-version }}
      cache-name:
        description: "The cache name used"
        value: ${{ inputs.cache-name }}

jobs:
  verify:
    name: 🔎 Lint and Test
    runs-on: self-hosted
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up node
        uses: meza/action-setup-node-pnpm@a2f4240b2835ddfaeb13b353e996e93832b5f47c # main
        with:
          node-version: ${{ inputs.node-version }}
          cache-name: ${{ inputs.cache-name }}
      - run: pnpm run ci
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          junit_files: ${{ inputs.junit-report-path }}
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        if: always()
        with:
          format: markdown
          output: file
          hide_complexity: false
          badge: true
          filename: ${{ inputs.cobertura-report-path }}
      - name: Publish code coverage report
        if: always()
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: echo "Need release? ${{ steps.get-next-version.outputs.new-release-published }}" >> $GITHUB_STEP_SUMMARY
