name: Set up Golang

on:
  workflow_call:
    inputs:
      go-version:
        description: "The version of node to use"
        required: false
        type: string
        default: "latest"

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        name: 🔧 Set up Node.js
        with:
          node-version: 'latest'
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        name: 🔧 Set up Go ${{ inputs.go-version }}
        with:
          go-version:  ${{ inputs.go-version }}

      - name: 📦 Install dependencies
        run: |
          go get .
          go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest

      - name: 🔍 Test with the Go CLI
        run: go test -json ./... | go-ctrf-json-reporter -output ctrf-report.json

      - name: 📝 Publish CTRF Test Summary Results
        run: npx github-actions-ctrf ctrf-report.json
        if: always()

      - name: ❌ Publish CTRF Failed Test Summary Results
        run: npx github-actions-ctrf failed ctrf-report.json
        if: always()

      - run: npx semantic-release --dry-run
        name: 🧮 Get next version number
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
