name: Lint and Test

on:
  workflow_call:
    inputs:
      command:
        description: "Which command to run when installing the dependencies? It will be appended to `npm ` Default: ci"
        default: install --no-audit --no-fund
        required: false
        type: string
      test:
        description: 'Run tests'
        required: false
        default: true
        type: boolean
      node-version:
        description: "The version of node to use"
        required: false
        type: string
        default: "latest"
      junit-report-path:
        description: "The path to the JUnit report"
        required: false
        type: string
        default: "reports/junit.xml"
      cobertura-report-path:
        description: "The path to the Cobertura report"
        required: false
        type: string
        default: "reports/coverage/cobertura-coverage.xml"
      cpdPath:
        description: "Where is your markdown cpd report generated to?"
        required: false
        type: string
        default: "reports/jscpd/jscpd-report.md"
      cache-name:
        description: "The name to assign to the cache"
        required: false
        type: string
        default: pure-dependencies
    secrets:
      GH_TOKEN:
        required: true
      NPM_TOKEN:
        required: false
    outputs:
      new-release-published:
        description: "If a new release was published"
        value: ${{ jobs.verify.outputs.new-release-published }}
      new-release-version:
        description: "The version of the new release"
        value: ${{ jobs.verify.outputs.new-release-version }}
      cache-name:
        description: "The cache name used"
        value: ${{ inputs.cache-name }}

jobs:
  verify:
    name: 🔎 Lint and Test
    runs-on: self-hosted
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up node
        uses: meza/action-setup-node-npm@eadf21e0155e62a54d3b72fb8530d5a12fa21146 # main
        with:
          command: ${{ inputs.command }}
          node-version: ${{ inputs.node-version }}
          cache-name: ${{ inputs.cache-name }}
      - run: npm run ci
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: inputs.test
        with:
          junit_files: ${{ inputs.junit-report-path }}
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        if: inputs.test
        with:
          format: markdown
          output: file
          hide_complexity: false
          badge: true
          filename: ${{ inputs.cobertura-report-path }}
      - name: Publish code coverage report
        if: inputs.test
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        if: (github.event_name == 'pull_request') && (inputs.test)
        with:
          recreate: true
          path: code-coverage-results.md
      - name: "Check cpd existence"
        id: cpd_exists
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: "${{ inputs.cpdPath }}"
      - name: Publish jscpd report
        if: (inputs.test) && (steps.cpd_exists.outputs.files_exists == 'true')
        run: cat ${{ inputs.cpdPath }} >> $GITHUB_STEP_SUMMARY
      - name: Add CPD Report PR Comment
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        if: (github.event_name == 'pull_request') && (inputs.test) && (steps.cpd_exists.outputs.files_exists == 'true')
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          recreate: true
          path: ${{ inputs.cpdPath }}
      - run: npx semantic-release --dry-run
        id: get-next-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: echo "Need release? ${{ steps.get-next-version.outputs.new-release-published }}" >> $GITHUB_STEP_SUMMARY
