name: Set up Node with PNPM

on:
  workflow_call:
    inputs:
      cache-name:
        description: "The name of the cache to use"
        required: true
        type: string
      node-version:
        description: "The version of node to use"
        required: false
        type: string
        default: "latest"

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ inputs.node-version }}

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Cache build helpers
        id: cache-build-data
        uses: pat-s/always-upload-cache@9a0d1c3e1a8260b05500f9b67a5be8f2a1299819 # v3.0.11
        if: always()
        env:
          cache-name: cache-build-data
        with:
          path: ./.cache
          key: ${{ runner.os }}-build-data-${{ inputs.cache-name }}

      - uses: pat-s/always-upload-cache@9a0d1c3e1a8260b05500f9b67a5be8f2a1299819 # v3.0.11
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ inputs.cache-name }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install --frozen-lockfile
